# Generated by Django 5.2.6 on 2025-11-09 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(choices=[(4, '4 years'), (5, '5 years'), (6, '6 years'), (7, '7 years'), (8, '8 years'), (9, '9 years'), (10, '10 years'), (11, '11 years'), (12, '12 years')])),
                ('favorite_genres', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_input', models.TextField(blank=True)),
                ('transcription', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('adventure', 'Adventure'), ('fairy_tale', 'Fairy Tale'), ('educational', 'Educational'), ('bedtime', 'Bedtime'), ('mystery', 'Mystery'), ('friendship', 'Friendship')], default='adventure', max_length=20)),
                ('length', models.CharField(choices=[('short', 'Short (3-5 min)'), ('medium', 'Medium (5-8 min)'), ('long', 'Long (8-12 min)')], default='medium', max_length=10)),
                ('age_group', models.IntegerField(default=6)),
                ('characters', models.CharField(blank=True, max_length=200)),
                ('setting', models.CharField(blank=True, max_length=200)),
                ('moral_lesson', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('ai_model_used', models.CharField(default='groq-llama', max_length=50)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('estimated_duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stories.storyrequest')),
            ],
        ),
        migrations.CreateModel(
            name='StorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_listened', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.generatedstory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.generatedstory')),
            ],
            options={
                'unique_together': {('user', 'story')},
            },
        ),
    ]
